### PR TITLE
Add options for Header, Footer, and additional global print options

### PR DESCRIPTION
**Pull request by obrienmn**
Options added for Headers, Footers, and some more global switches.

### CODE REVIEW

**Comment by obrienmn** [comment]
Funnily enough, I originally went to add the header and footer to the print options but second guessed it. Should've trusted my first instinct! 

Are you happy for them to still be encapsulated within their own classes and retrieved during the print options GetSwitches method?

With respect to the HTML encoding, I'm not 100% on how you'd like this to work, being that the SpecialCharsEncode method is inaccessible to the print options class. 

Do you see this being done as part of the ConvertAsync method, in much the same way the actual PDF's HTML is handled? Recognising of course that this would affect all switches. Or did you see the SpecialCharsEncode become more like a utility method that would be called on the two HTML switch properties before the switches even reach that point?

**Comment by pug-pelle-p** [comment]
Yeah I still think it should be encapsulated within their own classes but just in the PrintOptions, so it accessible like this: `renderer.PrintOptions.Header.LeftText = "Hello"`.
I think doing the encoding in the GetSwitches() method would be the easiest, and just make the SpecialCharsEncode method a utility class :)

**Comment by pug-pelle-p** [comment]
I just tried your code and realized that HTML property on footer and header isn't a property to pass in HTML, it's a property to pass in an URL, so it doesn't need to be encoded. Sorry for the confusion.

Maybe we should also rename the HTML -> HTMLUrl to make it clear that it expects an URL, not HTML?

**Comment by obrienmn** [comment]
No problem. Makes sense to rename the properties I think. The switch name is definitely a bit confusing.

This has been done.

**Comment by pug-pelle-p** [comment]
Awesome! Thanks for your contribution :)

**Comment by lwyatt** [comment]
Hey there!
Are you planning on pushing these changes up to Nuget?

Thanks
Luke

**Pull request merged**
